/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
#include <stdio.h>
/* Header for class com_xc_mysolib_jni_Calculator */

#ifndef _Included_com_xc_mysolib_jni_Calculator
#define _Included_com_xc_mysolib_jni_Calculator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xc_mysolib_jni_Calculator
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_xc_mysolib_jni_Calculator_add
  (JNIEnv *env, jobject thiz, jint a, jint b){
  return  a +  b;
}

/*
 * Class:     com_xc_mysolib_jni_Calculator
 * Method:    sub
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_xc_mysolib_jni_Calculator_sub
  (JNIEnv* env, jobject thiz, jint a, jint b){
  return  a- b;
}

/*
 * Class:     com_xc_mysolib_jni_Calculator
 * Method:    set
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_xc_mysolib_jni_Calculator_set
  (JNIEnv *env, jobject thiz, jstring string){
  printf("invoke set(String str) in C++ from mysolib.so \n");
  const char* str = env->GetStringUTFChars(string,NULL);
  env->ReleaseStringUTFChars(string,str);
}

/*
 * Class:     com_xc_mysolib_jni_Calculator
 * Method:    get
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xc_mysolib_jni_Calculator_get
  (JNIEnv *env, jobject thiz){
  printf("invoke get()in C++  from mysolib.so\n");
  return env->NewStringUTF("a string from mysolib.so");
}

#ifdef __cplusplus
}
#endif
#endif
