/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xc_mysolib_jni_Calculator */

#ifndef _Included_com_xc_mysolib_jni_Calculator
#define _Included_com_xc_mysolib_jni_Calculator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xc_mysolib_jni_Calculator
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_xc_mysolib_jni_Calculator_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_xc_mysolib_jni_Calculator
 * Method:    sub
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_xc_mysolib_jni_Calculator_sub
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_xc_mysolib_jni_Calculator
 * Method:    set
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_xc_mysolib_jni_Calculator_set
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_xc_mysolib_jni_Calculator
 * Method:    get
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xc_mysolib_jni_Calculator_get
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
